local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("AlayHub V1", "Serpent")
local Tab = Window:NewTab("Credits")
local Section = Tab:NewSection("!WARNING!")
local Section = Tab:NewSection("THESE SCRIPTS ARENT MINE,")
local Section = Tab:NewSection("LINKS TO SCRIPTS ARE IN BUTTON INFO")
local Section = Tab:NewSection("UI by xHeptc on GitHub")
local Section = Tab:NewSection("GUI by alayrc on Discord")
local Tab = Window:NewTab("Other GUIs")
local Section = Tab:NewSection("Other GUIs")
Section:NewButton("infinite yield fe", "https://cdn.wearedevs.net/scripts/Infinite%20Yield.txt", function() loadstring(game:HttpGet("https://cdn.wearedevs.net/scripts/Infinite%20Yield.txt"))()
end)
Section:NewButton("c00lgui v2 fe (skidded but cool)", "rbxassetid://9827584846", function() loadstring(game:GetObjects("rbxassetid://9827584846")[1].Source)()
end)
Section:NewButton("FreddyMenu", "https://pastebin.com/raw/zvdW5ii6", function() loadstring(game:HttpGet("https://pastebin.com/raw/zvdW5ii6"))()
end)
local Tab = Window:NewTab("troll")
local Section = Tab:NewSection("troll")
Section:NewButton("fling all (ONLY WORKS WITH PLAYER COLLISIONS)", "https://pastebin.com/raw/zqyDSUWX", function() loadstring(game:HttpGet("https://pastebin.com/raw/zqyDSUWX"))()
end)
Section:NewButton("fling gui (ONLY WORKS WITH PLAYER COLLISIONS)", "https://raw.githubusercontent.com/hellohellohell012321/KAWAII-FREAKY-FLING/main/kawaii_freaky_fling.lua", function() loadstring(game:HttpGet("https://raw.githubusercontent.com/hellohellohell012321/KAWAII-FREAKY-FLING/main/kawaii_freaky_fling.lua"))()
end)
local Tab = Window:NewTab("fun scripts")
local Section = Tab:NewSection("fun scripts")
Section:NewButton("turn into ball", "https://pastebin.com/raw/BZr9bGDy", function() loadstring(game:HttpGet("https://pastebin.com/raw/BZr9bGDy"))()
end)
local Tab = Window:NewTab("tsb scripts")
local Section = Tab:NewSection("tsb scripts")
Section:NewButton("gojo", "https://raw.githubusercontent.com/skibiditoiletfan2007/BaldyToSorcerer/main/Latest.lua", function() loadstring(game:HttpGet("https://raw.githubusercontent.com/skibiditoiletfan2007/BaldyToSorcerer/main/Latest.lua"))()
end)
Section:NewButton("sukana", "https://pastebin.com/raw/1yaXL0rA", function() loadstring(game:HttpGet("https://pastebin.com/raw/1yaXL0rA"))()
end)
local Tab = Window:NewTab("guis for other games")
local Section = Tab:NewSection("guis for other games")
Section:NewButton("rate my avatar", "https://raw.githubusercontent.com/hellohellohell012321/rate-my-avatar-gui/main/main.lua", function() loadstring(game:HttpGet("https://raw.githubusercontent.com/hellohellohell012321/rate-my-avatar-gui/main/main.lua"))()
end)
Section:NewButton("prison life", "https://zygomorphic-jobyna-impacthub-3d96c239.koyeb.app/main.lua", function() loadstring(game:HttpGet("https://zygomorphic-jobyna-impacthub-3d96c239.koyeb.app/main.lua"))()
end)